### ISSUE TITLE
Create other action is not accessible

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-workspaces#4]
The workspace **Create other** action is there in the package (_import-pages\(apps)\Workspace_ folder), but is not accessible from the UI.

### TODO
- [x] add the Create action to the _WorkspaceActions_ scenario
- [x] add missing images to the import-pages folder above (global\images subfolder): move them from TFS, old dev\BP branch (contentypegroup0.jpg, 1, 2, 3).
- [x] check if the action works

Link to the feature on the [old demo site](https://demo.sensenet.com/workspaces/Sales/californiasalesworkspace?action=Create&back=%2Fworkspaces%2FSales%2Fcaliforniasalesworkspace).

**Comment by VargaJoe** [comment]
I will fix this oldie
